"""empty message

Revision ID: f372a655fd16
Revises: 
Create Date: 2021-11-16 17:06:17.914621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f372a655fd16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propietario',
    sa.Column('idpropietario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('direccion', sa.String(length=45), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idpropietario'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_mascota',
    sa.Column('idtipo_mascota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idtipo_mascota')
    )
    op.create_table('mascotas',
    sa.Column('idmascota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('tipo_mascota', sa.Integer(), nullable=True),
    sa.Column('propietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propietario'], ['propietario.idpropietario'], ),
    sa.ForeignKeyConstraint(['tipo_mascota'], ['tipo_mascota.idtipo_mascota'], ),
    sa.PrimaryKeyConstraint('idmascota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    op.drop_table('tipo_mascota')
    op.drop_table('propietario')
    # ### end Alembic commands ###
